/**
 * TEKNİK TERİM SÖZLÜĞÜ — İngilizce -> Türkçe
 *
 * Kaynak verilerde Türkçe yok. Teknik özellik etiketleri sınırlı ve
 * tekrarlı olduğu için (1041 farklı etiket, ilk 300'ü satırların %90'ı)
 * elle çevrilerek gerçek Türkçe elde edilir.
 *
 * Sayı + birim değerleri ("230 V", "900 mm", "50 Hz") çevrilmez.
 */

export const ETIKET = {
  // --- genel ---
  "Material": "Malzeme",
  "Important information": "Önemli bilgi",
  "Properties": "Özellikler",
  "Including": "Dahil olanlar",
  "Not included in delivery": "Teslimata dahil değil",
  "Delivery state": "Teslim durumu",
  "Available on request": "Talep üzerine",
  "Series": "Seri",
  "Model": "Model",
  "Type": "Tip",
  "Design": "Tasarım",
  "Designed for": "Kullanım alanı",
  "Application area": "Kullanım alanı",
  "Norm": "Norm",
  "Gastronorm": "Gastronorm",
  "GN-capable": "GN uyumlu",
  "Capacity GN": "GN kapasitesi",
  "Suitable for": "Uygunluk",
  "Functions": "Fonksiyonlar",
  "Set comprises": "Set içeriği",
  "Operation": "Kullanım",
  "Operating mode": "Çalışma şekli",
  "Assembly type": "Montaj tipi",
  "Can be installed": "Montaj edilebilir",
  "Order quantity unit": "Sipariş birimi",
  "Colour": "Renk",
  "Surface": "Yüzey",
  "Stackable": "Üst üste konabilir",
  "Double-walled": "Çift cidarlı",
  "Insulation": "Yalıtım",
  "Programming": "Programlama",
  "Regulation of": "Ayar",

  // --- elektrik ---
  "Power": "Güç",
  "Voltage": "Voltaj",
  "Frequency": "Frekans",
  "Protection class": "Koruma sınıfı",
  "Equipment connection": "Cihaz bağlantısı",
  "Connection cable type": "Bağlantı kablosu tipi",
  "Length cable": "Kablo uzunluğu",
  "Control lamp": "Kontrol lambası",
  "Control unit": "Kumanda ünitesi",
  "ON/OFF switch": "Açma/kapama düğmesi",
  "Digital display": "Dijital gösterge",
  "LED display": "LED gösterge",
  "Display": "Gösterge",
  "Temperature display": "Sıcaklık göstergesi",
  "Filling level display": "Seviye göstergesi",
  "Timer": "Zamanlayıcı",
  "Time setting from": "Süre ayarı (alt sınır)",
  "Time setting to": "Süre ayarı (üst sınır)",
  "Energy consumption kWh / an": "Enerji tüketimi kWh/yıl",
  "Energy consumption kWh / 24 h": "Enerji tüketimi kWh/24 saat",
  "Energy efficiency class": "Enerji sınıfı",
  "Output max.": "Azami çıkış",
  "Output / hour max.": "Saatlik azami kapasite",
  "Motor output": "Motor gücü",
  "Motor protection": "Motor koruması",
  "Overload protection": "Aşırı yük koruması",
  "Overheating protection": "Aşırı ısınma koruması",
  "Safety switch": "Emniyet şalteri",
  "Safety thermostat": "Emniyet termostatı",
  "Thermostat": "Termostat",
  "Speed control": "Hız ayarı",
  "Rpm max.": "Azami devir",
  "Fan speed": "Fan hızı",
  "Fan regulation": "Fan ayarı",
  "USB connection": "USB bağlantısı",
  "Lock button (child protection)": "Kilit tuşu (çocuk koruması)",
  "Door contact switch": "Kapı kontak şalteri",
  "Heating element": "Isıtıcı rezistans",
  "Heating element in stainless steel": "Paslanmaz çelik rezistans",
  "Heating type": "Isıtma tipi",
  "Heat source": "Isı kaynağı",
  "Heat source type": "Isı kaynağı tipi",
  "Heat-up time": "Isınma süresi",
  "Run-time": "Çalışma süresi",

  // --- sıcaklık ---
  "Temperature range": "Sıcaklık aralığı",
  "Temperature range from": "Sıcaklık aralığı (alt)",
  "Temperature range to": "Sıcaklık aralığı (üst)",
  "Temperature control": "Sıcaklık kontrolü",
  "Number of temperature levels": "Sıcaklık kademesi sayısı",
  "Temperature resistant to": "Isı dayanımı",
  "Ambient temperature": "Ortam sıcaklığı",
  "Core temperature sensor connection": "Çekirdek sıcaklık sensörü bağlantısı",
  "Warm-keeping function": "Sıcak tutma fonksiyonu",
  "Climate class": "İklim sınıfı",

  // --- soğutma ---
  "Cooling": "Soğutma",
  "Coolant": "Soğutucu akışkan",
  "Refrigerant": "Soğutucu akışkan",
  "GWP": "GWP (küresel ısınma potansiyeli)",
  "Automatic defrosting function": "Otomatik defrost",
  "Drip water evaporation": "Yoğuşma suyu buharlaştırma",
  "Interior lighting": "İç aydınlatma",
  "Lighting": "Aydınlatma",
  "Lamps (number + watt)": "Lamba (adet + watt)",

  // --- ölçüler ---
  "Content": "Hacim",
  "Useful content": "Kullanılabilir hacim",
  "Storage capacity": "Depolama kapasitesi",
  "Diameter": "Çap",
  "Inside diameter": "İç çap",
  "Height inside": "İç yükseklik",
  "Inside height": "İç yükseklik",
  "Width inside": "İç genişlik",
  "Depth inside": "İç derinlik",
  "Clear height": "Net yükseklik",
  "Design inside": "İç tasarım",
  "Material inside": "İç malzeme",
  "Height-adjustable feet": "Ayarlanabilir ayaklar",
  "Height-adjustable from": "Yükseklik ayarı (alt)",
  "Height-adjustable to": "Yükseklik ayarı (üst)",
  "Swivel casters": "Döner tekerlek",
  "Diameter casters": "Tekerlek çapı",
  "Wheel buffer": "Tekerlek tamponu",
  "Carrying handle": "Taşıma kolu",
  "With handle(s)": "Kollu",
  "Handle properties": "Kol özellikleri",
  "Material handle(s)": "Kol malzemesi",
  "Board thickness": "Levha kalınlığı",
  "Material thickness": "Malzeme kalınlığı",
  "Total load-bearing capacity, max.": "Azami toplam taşıma kapasitesi",
  "Load-bearing capacity max.": "Azami taşıma kapasitesi",
  "Load capacity per hob": "Ocak başına taşıma kapasitesi",

  // --- kapı / çekmece / raf ---
  "Number of doors": "Kapı sayısı",
  "Type of door": "Kapı tipi",
  "Door hinge side": "Kapı menteşe yönü",
  "Door hinge side can be changed": "Kapı yönü değiştirilebilir",
  "Position of the door": "Kapı konumu",
  "Door double-walled": "Çift cidarlı kapı",
  "Number of drawers": "Çekmece sayısı",
  "Format drawers": "Çekmece ölçüsü",
  "Norm-format drawers": "Norm ölçülü çekmece",
  "Depth drawer": "Çekmece derinliği",
  "Load-bearing capacity per drawer max.": "Çekmece başına azami taşıma",
  "Number of shelves": "Raf sayısı",
  "Design shelves": "Raf tasarımı",
  "Width shelves": "Raf genişliği",
  "Depth shelves": "Raf derinliği",
  "Shelf type": "Raf tipi",
  "Height-adjustable shelves": "Ayarlanabilir raflar",
  "Base shelf": "Alt raf",
  "Design base shelf": "Alt raf tasarımı",
  "Height-adjustable base shelf": "Ayarlanabilir alt raf",
  "Load-bearing base shelf, max.": "Alt raf azami taşıma",
  "Intermediate shelf": "Ara raf",
  "Number of intermediate shelves": "Ara raf sayısı",
  "Type of intermediate shelves": "Ara raf tipi",
  "Design intermediate shelf": "Ara raf tasarımı",
  "Width intermediate shelf": "Ara raf genişliği",
  "Depth intermediate shelf": "Ara raf derinliği",
  "Height-adjustable intermediate shelves": "Ayarlanabilir ara raflar",
  "Height-adjustable immediate shelves": "Ayarlanabilir ara raflar",
  "Dimensions of intermediate shelves": "Ara raf ölçüleri",
  "Intermediate shelves with price rails": "Fiyat raylı ara raflar",
  "With price strips": "Fiyat şeritli",
  "Advertising display": "Reklam panosu",
  "Lockable": "Kilitlenebilir",

  // --- tezgâh / çalışma yüzeyi ---
  "Worktop surface": "Tezgâh yüzeyi",
  "Design worktop": "Tezgâh tasarımı",
  "Load-bearing capacity worktop, max.": "Tezgâh azami taşıma kapasitesi",
  "Width work surface": "Çalışma yüzeyi genişliği",
  "Depth work surface": "Çalışma yüzeyi derinliği",
  "Material work surface": "Çalışma yüzeyi malzemesi",
  "Width surface": "Yüzey genişliği",
  "Depth surface": "Yüzey derinliği",
  "Diameter surface": "Yüzey çapı",
  "Reinforced edge": "Takviyeli kenar",
  "Stopper edge": "Durdurucu kenar",
  "Splash protection": "Sıçrama koruması",
  "Germ guard": "Hijyen bariyeri",
  "Front pane": "Ön cam",
  "Window": "Pencere",
  "Type of glass": "Cam tipi",
  "Safety glass": "Emniyet camı",
  "Width glass field": "Cam alan genişliği",
  "Depth glass field": "Cam alan derinliği",
  "Sub-counter unit type": "Tezgâh altı ünite tipi",
  "Width sub-counter unit": "Tezgâh altı ünite genişliği",
  "Depth sub-counter unit": "Tezgâh altı ünite derinliği",
  "Height sub-counter unit": "Tezgâh altı ünite yüksekliği",
  "Can be fitted below the counter": "Tezgâh altına montaj",

  // --- pişirme ---
  "Number of hobs": "Ocak gözü sayısı",
  "Type of hobs": "Ocak tipi",
  "Size hobs": "Ocak ölçüsü",
  "Material hob": "Ocak malzemesi",
  "Distribution of hobs": "Ocak yerleşimi",
  "Output hob(s) max.": "Ocak azami gücü",
  "Number of heating zones": "Isıtma bölgesi sayısı",
  "Heating zones can be controlled separately": "Bölgeler ayrı kontrol edilebilir",
  "Number of output levels": "Kademe sayısı",
  "Pot recognition": "Tencere algılama",
  "Induction-suitable": "İndüksiyona uygun",
  "Gas type": "Gaz tipi",
  "Gas burner": "Gaz brülörü",
  "Ignition type": "Ateşleme tipi",
  "Pilot flame": "Pilot alev",
  "Flame protection filter": "Alev koruma filtresi",
  "Tilting": "Devirmeli",
  "Inner pot": "İç kazan",
  "Material cooking chamber": "Pişirme haznesi malzemesi",
  "Number of cooking programs": "Pişirme programı sayısı",
  "Oven functions": "Fırın fonksiyonları",
  "Oven properties": "Fırın özellikleri",
  "Multifunctional oven": "Çok fonksiyonlu fırın",
  "Oven connected load": "Fırın bağlantı gücü",
  "Width oven": "Fırın genişliği",
  "Height oven": "Fırın yüksekliği",
  "Depth oven": "Fırın derinliği",
  "Upper / lower heat can be controlled separately": "Üst/alt ısı ayrı kontrol edilebilir",
  "Number of baking chambers": "Pişirme haznesi sayısı",
  "Material baking chamber": "Pişirme haznesi malzemesi",
  "Number of baking units": "Pişirme ünitesi sayısı",
  "Design baking tray(s)": "Tepsi tasarımı",
  "Material baking trays": "Tepsi malzemesi",
  "Baking trays can be rotated": "Tepsiler döndürülebilir",
  "Distance between trays": "Tepsiler arası mesafe",
  "Tray slide": "Tepsi rayı",
  "Number of fans": "Fan sayısı",
  "Number of fan motors/exhaust air outputs": "Fan motoru / atık hava çıkışı sayısı",
  "Roasting surface design": "Pişirme yüzeyi tasarımı",
  "Material roasting surface": "Pişirme yüzeyi malzemesi",
  "Width roasting surface": "Pişirme yüzeyi genişliği",
  "Depth roasting surface": "Pişirme yüzeyi derinliği",
  "Design grill surface": "Izgara yüzeyi tasarımı",
  "Full-surface": "Tam yüzey",
  "Grease collection tank": "Yağ toplama haznesi",
  "Grease release tap": "Yağ boşaltma musluğu",
  "Plate height max.": "Azami tabak yüksekliği",
  "Height-adjustable grid": "Ayarlanabilir ızgara",
  "Can be loaded from both sides": "İki taraftan yüklenebilir",
  "Diameter perforation": "Delik çapı",

  // --- fritöz / hazne ---
  "Number of tanks": "Hazne sayısı",
  "Tank volume": "Hazne hacmi",
  "Width tank": "Hazne genişliği",
  "Height tank": "Hazne yüksekliği",
  "Depth tank": "Hazne derinliği",
  "Tank heater": "Hazne ısıtıcısı",
  "Number of baskets": "Sepet sayısı",
  "Basket size": "Sepet ölçüsü",
  "Basket content": "Sepet hacmi",
  "Basket dimensions": "Sepet ölçüleri",
  "Width basket": "Sepet genişliği",
  "Depth basket": "Sepet derinliği",
  "Height basket": "Sepet yüksekliği",
  "Depth container": "Kap derinliği",
  "Depth GN container max.": "Azami GN kap derinliği",
  "Basin size, GN format": "Hazne ölçüsü, GN formatı",
  "Compartment size": "Bölme ölçüsü",
  "Beaker capacity": "Hazne kapasitesi",
  "Dry-run protection": "Kuru çalışma koruması",

  // --- su / bulaşık ---
  "Water connection": "Su bağlantısı",
  "Water supply": "Su besleme",
  "Water supply tap": "Su besleme musluğu",
  "Water outlet": "Su çıkışı",
  "Water drain tap": "Su tahliye musluğu",
  "Drain tap": "Tahliye musluğu",
  "Sink tap": "Evye bataryası",
  "Water pressure": "Su basıncı",
  "Water intake temperature": "Giriş suyu sıcaklığı",
  "Water consumption at 2 bar": "2 barda su tüketimi",
  "Water softener": "Su yumuşatıcı",
  "Water bowl for air humidification": "Nemlendirme su haznesi",
  "Number of wash programs": "Yıkama programı sayısı",
  "Cleaning agent dosing pump": "Deterjan dozaj pompası",
  "Clear rinsing dosing pump": "Parlatıcı dozaj pompası",
  "With cleaning system": "Temizleme sistemli",
  "Lye pump": "Tahliye pompası",
  "Boiler heater": "Boyler ısıtıcısı",
  "Decalcification signal": "Kireç uyarısı",
  "Dishwasher-suitable": "Bulaşık makinesinde yıkanabilir",

  // --- havalandırma / filtre ---
  "Number of filters": "Filtre sayısı",
  "Material filter": "Filtre malzemesi",
  "Vapour extractor": "Buhar emici",
  "Max. air throughput": "Azami hava debisi",
  "With motor": "Motorlu",

  // --- hazırlık / hamur ---
  "Cutting thickness": "Kesme kalınlığı",
  "Cutting surface": "Kesme yüzeyi",
  "Design knife": "Bıçak tasarımı",
  "Diameter knife": "Bıçak çapı",
  "Juice groove": "Su kanalı",
  "Max. dough quantity": "Azami hamur miktarı",
  "Mixing bowl volume": "Karıştırma kabı hacmi",
  "Mixing bowl detachable": "Çıkarılabilir karıştırma kabı",
  "Material mixing bowl(s)": "Karıştırma kabı malzemesi",
  "Material dough hook": "Hamur kancası malzemesi",
  "Swivel head": "Devrilir kafa",
  "Matches the KitchenAid": "KitchenAid ile uyumlu",
  "Pasta size": "Makarna ölçüsü",
  "Pasta type": "Makarna tipi",
  "Waffle size": "Waffle ölçüsü",
  "Waffle form": "Waffle şekli",
  "Pizza capacity": "Pizza kapasitesi",
  "Pizza oven series": "Pizza fırını serisi",
  "Production max.": "Azami üretim",
  "Minimum brewing quantity": "Asgari demleme miktarı",
  "Spoon recess": "Kaşık yuvası",
  "Silicone seal": "Silikon conta",
  "Material lid": "Kapak malzemesi",
  "Lid properties": "Kapak özellikleri",
  "Width crucible": "Pota genişliği",
  "Height crucible": "Pota yüksekliği",
  "Material crucible": "Pota malzemesi",
};

/** Değerler — çoğu sayı+birim olduğu için yalnız metin olanlar çevrilir. */
export const DEGER = {
  "Yes": "Evet",
  "yes": "Evet",
  "No": "Hayır",
  "no": "Hayır",
  "-": "-",
  "Stainless steel": "Paslanmaz çelik",
  "Chrome-nickel steel": "Krom-nikel çelik",
  "CNS 18/10": "CNS 18/10 paslanmaz çelik",
  "Plastic": "Plastik",
  "Silver": "Gümüş",
  "Black": "Siyah",
  "White": "Beyaz",
  "Grey": "Gri",
  "Red": "Kırmızı",
  "Blue": "Mavi",
  "Aluminium": "Alüminyum",
  "Glass": "Cam",
  "Wood": "Ahşap",
  "Electro": "Elektrikli",
  "Gas": "Gazlı",
  "Induction": "İndüksiyon",
  "Pluggable": "Fişli",
  "Permanently mounted": "Sabit montaj",
  "Upright unit": "Dikey ünite",
  "Building kit (simple assembly)": "Montaj kiti (kolay kurulum)",
  "Assembled": "Monte edilmiş",
  "Full-surface": "Tam yüzey",
  "Smooth": "Düz",
  "Ribbed": "Nervürlü",
  "Grooved": "Oluklu",
  "ON/OFF": "Açma/kapama",
  "Digital": "Dijital",
  "Analogue": "Analog",
  "Manual": "Manuel",
  "Automatic": "Otomatik",
  "Electronic": "Elektronik",
  "Mechanical": "Mekanik",
  "Left": "Sol",
  "Right": "Sağ",
  "Front": "Ön",
  "Rear": "Arka",
  "Top": "Üst",
  "Bottom": "Alt",
  "Hinged": "Menteşeli",
  "Sliding": "Sürgülü",
  "Removable": "Çıkarılabilir",
  "Fixed": "Sabit",
  "Adjustable": "Ayarlanabilir",
  "Optional": "Opsiyonel",
  "Included": "Dahil",
  "On request": "Talep üzerine",
  "Piece": "Adet",
  "Set": "Set",
  "Pair": "Çift",
  "Single-walled": "Tek cidarlı",
  "Double-walled": "Çift cidarlı",
  "Static": "Statik",
  "Ventilated": "Fanlı",
  "Circulating air": "Sirkülasyonlu hava",
  "Toggle": "Devirmeli anahtar",
  "Knob": "Düğme",
  "Table-top unit": "Tezgâh üstü ünite",
  "No perforation": "Deliksiz",
  "Perforated": "Delikli",
  "Top Line": "Top Line",
  "Basic Line": "Basic Line",
  "Heat up": "Isıtma",
  "Silver grey": "Gümüş gri",
  "Silk matt": "İpek mat",
  "High-gloss": "Parlak",
  "Matt": "Mat",
  "Open": "Açık",
  "Closed": "Kapalı",
  "Welded": "Kaynaklı",
  "Screwed": "Vidalı",
  "Stepless": "Kademesiz",
  "Piezo ignition": "Piezo ateşleme",
  "Electric ignition": "Elektrikli ateşleme",
  "GN containers": "GN kaplar",
  "Electronic": "Elektronik",
  "Special production": "Özel üretim",
  "4 swivel casters, 2 with brake": "4 döner tekerlek, 2'si frenli",
  "2 with brake": "2'si frenli",
  "with brake": "frenli",
  "Rounded corners": "Yuvarlatılmış köşeler",
  "Sharp corners": "Keskin köşeler",
  "Brushed": "Fırçalanmış",
  "Polished": "Parlatılmış",
  "Painted": "Boyalı",
  "Coated": "Kaplamalı",
  "Enamelled": "Emaye",
  "Chromed": "Krom kaplama",
  "Cast iron": "Döküm demir",
  "Steel": "Çelik",
  "Copper": "Bakır",
  "Brass": "Pirinç",
  "Rubber": "Kauçuk",
  "Silicone": "Silikon",
  "Ceramic": "Seramik",
  "Melamine": "Melamin",
  "Polypropylene": "Polipropilen",
  "Polycarbonate": "Polikarbonat",
  "Tempered glass": "Temperli cam",
  "Double glazing": "Çift cam",
  "Single glazing": "Tek cam",
  "Curved": "Kavisli",
  "Straight": "Düz",
  "Vertical": "Dikey",
  "Horizontal": "Yatay",
  "Front and rear": "Ön ve arka",
  "Both sides": "İki taraf",
  "One side": "Tek taraf",
  "Central": "Merkezi",
  "Separate": "Ayrı",
  "Integrated": "Entegre",
  "External": "Harici",
  "Internal": "Dahili",
  "Standard": "Standart",
  "Heavy duty": "Ağır hizmet",
  "Compact": "Kompakt",
  "Mobile": "Hareketli",
  "Wall-mounted": "Duvara monte",
  "Floor-standing": "Yere montaj",
  "Built-in": "Ankastre",
  "Freestanding": "Serbest duran",
  "Drop-in": "Gömme",
  "None": "Yok",
  "All": "Tümü",
  "Various": "Çeşitli",
  "On/Off": "Açma/kapama",
  "Continuous": "Sürekli",
  "Intermittent": "Aralıklı",
  "Front side": "Ön taraf",
  "Rear side": "Arka taraf",
  "Left side": "Sol taraf",
  "Right side": "Sağ taraf",
};

/** Sayı + birim mi? ("230 V", "900 mm", "50/60 Hz", "-2°C to +2°C") */
const SAYISAL = /^[\d\s.,+°/x×"'-]*(mm|cm|m|kg|g|l|ml|w|kw|v|hz|bar|°c|°f|rpm|%|min|h|gn|nac|"|inch)?[\d\s.,+°/x×"'-]*$/i;

/**
 * Dilden bağımsız kodlar — çevrilmez, olduğu gibi geçer.
 * Norm/standart (EN 631, DIN, ISO), koruma sınıfı (IPX3), soğutucu gazı
 * (R290), ölçü (3/4"), model/seri adları.
 */
const KOD = /^(EN|DIN|ISO|NSF|CE|UL)\s*\d|^IPX?\d|^R\d{2,4}|^[A-Z]{1,3}\d{2,}|^\d+\/\d+"|^GN\s|^Ø/i;

/** "Stainless steel ,Plastic" gibi birleşik değerleri parçala */
const AYIRICI = /\s*,\s*/;

export function degerCevir(v) {
  const t = String(v ?? "").trim();
  if (!t) return t;
  if (DEGER[t]) return DEGER[t];
  if (SAYISAL.test(t)) return t;
  if (KOD.test(t)) return t;

  // birleşik değer: her parçayı ayrı çöz, hepsi çözülürse birleştir
  if (AYIRICI.test(t)) {
    const parcalar = t.split(AYIRICI).map((x) => x.trim()).filter(Boolean);
    if (parcalar.length > 1 && parcalar.length <= 4) {
      const cevrilen = parcalar.map((x) =>
        DEGER[x] ?? (SAYISAL.test(x) || KOD.test(x) ? x : null),
      );
      if (cevrilen.every(Boolean)) return cevrilen.join(", ");
    }
  }
  return null;                              // çevrilemedi
}

export function etiketCevir(l) {
  const t = String(l ?? "").trim();
  return ETIKET[t] ?? kalipCevir(t) ?? null;
}

/* ================================================================
   KALIP ÇÖZÜCÜ
   "Width grid", "Depth drawer", "Number of cupboards" gibi etiketler
   kalıplıdır. Her birleşimi tek tek yazmak yerine isim sözlüğü +
   kalıp kuralıyla çözülür.
   ================================================================ */

export const ISIM = {
  "grid": "ızgara", "grids": "ızgara", "grille shelves": "ızgara raf",
  "pan": "tava", "pans": "tava", "pan without lid": "kapaksız tava",
  "frame": "çerçeve", "basket": "sepet", "basket 1": "1. sepet", "basket 2": "2. sepet",
  "boiler": "boyler", "boilers": "boyler", "drain": "tahliye",
  "plastic insert": "plastik iç kap", "cupboard": "dolap", "cupboards": "dolap",
  "glass top": "cam üst", "crêpe trays": "krep plakası", "crêpe plates": "krep plakası",
  "shovel": "kürek", "cup shaft": "bardak haznesi", "drawer": "çekmece", "drawers": "çekmece",
  "hob": "ocak", "hob(s)": "ocak", "hobs": "ocak",
  "hob right": "sağ ocak", "hob left": "sol ocak", "hob front": "ön ocak", "hob rear": "arka ocak",
  "all hobs left": "soldaki tüm ocaklar", "hob rear left": "arka sol ocak",
  "inner container": "iç kap", "containers": "kap", "container": "kap",
  "inside container": "iç kap", "of each container": "her kap",
  "grill surface": "ızgara yüzeyi", "grills areas": "ızgara alanı",
  "grill plates": "ızgara plakası", "grill units": "ızgara ünitesi",
  "lower grill plate": "alt ızgara plakası", "upper grill plate": "üst ızgara plakası",
  "upper grill plate, each": "üst ızgara plakası (her biri)",
  "temperature sensor": "sıcaklık sensörü", "temperature zones": "sıcaklık bölgesi",
  "mixing beaker": "karıştırma haznesi", "mixing bowl(s)": "karıştırma kabı",
  "mixing rod": "karıştırma çubuğu", "mixing disk": "karıştırma diski",
  "mixers": "mikser", "mixer": "mikser", "mixer blades": "mikser bıçağı",
  "intermediate shelf bottom": "alt ara raf", "intermediate shelf middle": "orta ara raf",
  "intermediate shelf top": "üst ara raf", "intermediate shelf": "ara raf",
  "intermediate shelves": "ara raf",
  "table top": "tabla", "surface": "yüzey", "of surface": "yüzey",
  "warming plate": "ısıtma plakası", "warming plates": "ısıtma plakası",
  "warming plate(s)": "ısıtma plakası", "warming station(s)": "ısıtma istasyonu",
  "warming stations": "ısıtma istasyonu",
  "glass cylinder": "cam silindir", "transport area": "taşıma alanı",
  "clearing basin": "boşaltma haznesi", "clearing groove": "boşaltma kanalı",
  "basin": "hazne", "plates": "tabak", "cups": "fincan",
  "heating elements": "rezistans", "heating element": "rezistans",
  "heating levels": "ısıtma kademesi", "heating circuits": "ısıtma devresi",
  "heating system": "ısıtma sistemi", "heat sources": "ısı kaynağı",
  "heat lamps": "ısı lambası", "heated tubes": "ısıtma borusu",
  "per heated tube": "ısıtma borusu başına",
  "flow to": "akış (üst)", "flow from": "akış (alt)", "base": "taban",
  "wok insert": "wok iç kabı", "cooking phases": "pişirme aşaması",
  "roll": "rulo", "control": "kumanda", "filling shaft": "doldurma haznesi",
  "magnetrons": "magnetron", "bottom": "alt", "top": "üst",
  "burners": "brülör", "pots": "tencere", "bean container": "çekirdek haznesi",
  "bean containers": "çekirdek haznesi", "per sheet": "tepsi başına",
  "of ice container": "buz haznesi", "ice cube": "buz küpü", "ice cube sizes": "buz küpü ölçüsü",
  "table borehole": "masa deliği", "dispensers": "dağıtıcı", "of bowls": "kâse",
  "fuel past containers": "yakıt haznesi", "polishing heads": "parlatma kafası",
  "without casters": "tekersiz", "feet": "ayak", "without feet": "ayaksız",
  "crucible": "pota", "grinder funnel": "değirmen hunisi", "of grinder": "değirmen",
  "gears": "vites", "disks": "disk", "capacity": "kapasite", "skewers": "şiş",
  "tube": "boru", "weighing surface": "tartım yüzeyi",
  "toast bars": "tost yuvası", "with open lid": "kapak açıkken",
  "levels": "kademe", "inside, each": "iç (her biri)",
  "of display field": "gösterge alanı", "slits": "yarık",
  "browning levels": "kızartma kademesi", "when activated, hob rear": "arka ocak açıkken",
  "without rinsing fittings": "durulama armatürsüz",
  "cooking crockery": "pişirme kabı", "when hood is open": "kaput açıkken",
  "when door is open": "kapı açıkken", "niches": "niş",
  "welded joints": "kaynak noktası", "cooling device": "soğutma ünitesi",
  "of splash protection": "sıçrama koruması", "of knife": "bıçak",
  "rollers": "silindir", "dough rollers": "hamur silindiri",
  "can": "kutu", "can(s)": "kutu", "per can": "kutu başına", "/ can": "kutu başına",
  "salamander heating zones": "salamander ısıtma bölgesi",
  "griddle plate heating zones": "pleyt ısıtma bölgesi",
  "tape fasteners": "bant tutucu", "cable": "kablo", "taps": "musluk",
  "pumps": "pompa", "railing": "korkuluk", "of cutlery trays": "çatal-bıçak tepsisi",
  "ovens": "fırın", "plate holders": "tabak tutucu",
  "dies/stamps": "kalıp", "casters": "tekerlek",
  "of popcorn chamber floor": "patlatma haznesi tabanı",
  "coffee grounds": "kahve telvesi", "measuring points": "ölçüm noktası",
  "rows": "sıra", "of emulsifying disc": "emülsiyon diski",
  "milk refrigerator": "süt soğutucu", "cutting inserts": "kesme aparatı",
  "magnetic strips": "mıknatıslı şerit", "sub-counter unit size left": "sol tezgâh altı ünite ölçüsü",
  "sub-counter unit size right": "sağ tezgâh altı ünite ölçüsü",
  "/ hour": "saatte", "max.": "azami",
};

const KALIPLAR = [
  [/^Width\s+(.+)$/i, (x) => `${x} genişliği`],
  [/^Depth\s+(.+)$/i, (x) => `${x} derinliği`],
  [/^Height\s+(.+)$/i, (x) => `${x} yüksekliği`],
  [/^Diameter\s+(.+)$/i, (x) => `${x} çapı`],
  [/^Number of\s+(.+)$/i, (x) => `${x} sayısı`],
  [/^Material\s+(.+)$/i, (x) => `${x} malzemesi`],
  [/^Type of\s+(.+)$/i, (x) => `${x} tipi`],
  [/^Design\s+(.+)$/i, (x) => `${x} tasarımı`],
  [/^Size\s+(.+)$/i, (x) => `${x} ölçüsü`],
  [/^Volume\s+(.+)$/i, (x) => `${x} hacmi`],
  [/^Content\s+(.+)$/i, (x) => `${x} hacmi`],
  [/^Format\s+(.+)$/i, (x) => `${x} formatı`],
  [/^Output\s+(.+)$/i, (x) => `${x} gücü`],
  [/^Distance between\s+(.+)$/i, (x) => `${x} arası mesafe`],
  [/^Position of the\s+(.+)$/i, (x) => `${x} konumu`],
];

/** Kalıp + isim sözlüğüyle çöz; olmazsa null. */
export function kalipCevir(etiket) {
  let t = String(etiket ?? "").trim();
  if (!t) return null;

  // sondaki ", max." / " max." ayrılır, sonuna "azami" eklenir
  let azami = false;
  const m = t.match(/^(.*?),?\s*max\.?$/i);
  if (m && m[1] && /max/i.test(t)) { t = m[1].trim(); azami = true; }

  for (const [kalip, kur] of KALIPLAR) {
    const g = t.match(kalip);
    if (!g) continue;
    const isim = ISIM[g[1].trim().toLowerCase()];
    if (!isim) return null;
    const sonuc = kur(isim);
    return azami ? `Azami ${sonuc}` : sonuc;
  }
  return null;
}

/* ================================================================
   ÜRÜN ADI ÇEVİRİSİ
   Adlar "ürün tipi + model/ölçü" biçiminde. Tip kısmı çevrilir,
   model kodu ve ölçüler olduğu gibi kalır ("Deep fat fryer BF 30E"
   -> "Fritöz BF 30E"). En uzun eşleşme önce denenir.
   ================================================================ */
export const URUN_TIPI = {
  "deep fat fryer": "Fritöz", "deep frying basket": "Fritöz sepeti",
  "pastries deep fat fryer": "Pastane fritözü",
  "work table": "Çalışma tezgâhı", "worktable": "Çalışma tezgâhı",
  "work cabinet": "Çalışma dolabı", "work cabinets": "Çalışma dolapları",
  "wall shelves": "Duvar rafı", "wall shelf": "Duvar rafı",
  "wall hanging cabinets": "Duvar dolabı", "wall cabinet": "Duvar dolabı",
  "wall-mounted hood": "Duvar tipi davlumbaz", "wall mounted hood": "Duvar tipi davlumbaz",
  "box model hood": "Kutu tip davlumbaz", "exhaust hood": "Davlumbaz",
  "extractor hood": "Aspiratörlü davlumbaz",
  "griddle plate": "Pleyt ızgara", "electric griddle": "Elektrikli pleyt",
  "contact grill": "Kontakt ızgara", "lava stone grill": "Lavataş ızgara",
  "chicken grill": "Tavuk ızgarası", "table-top grill": "Tezgâh üstü ızgara",
  "salamander": "Salamander",
  "combi steamer": "Kombi fırın", "convection oven": "Konveksiyonlu fırın",
  "pizza oven": "Pizza fırını", "deck oven": "Taş fırın",
  "high-speed oven": "Hızlı fırın", "microwave oven": "Mikrodalga fırın",
  "gas stove": "Gazlı ocak", "gas cooker": "Gazlı ocak", "electric cooker": "Elektrikli ocak",
  "induction cooker": "İndüksiyonlu ocak", "ceramic cooker": "Seramik ocak",
  "stock-pot stove": "Kazan ocağı", "cooking station": "Pişirme istasyonu",
  "boiling kettle": "Pişirme kazanı", "soup kettle": "Çorba kazanı",
  "pasta cooker": "Makarna pişirici", "rice cooker": "Pilav pişirici",
  "tilting frying pan": "Devrilir tava", "multi pan": "Çok amaçlı tava",
  "refrigerated counter": "Soğutmalı tezgâh", "refrigerated display": "Soğutmalı teşhir",
  "refrigerator": "Buzdolabı", "deep freezer": "Derin dondurucu", "freezer": "Dondurucu",
  "mini cooler": "Mini soğutucu", "wine cooler": "Şarap soğutucu",
  "bottle cooler": "Şişe soğutucu", "barcooler": "Bar soğutucu",
  "ice cube maker": "Buz makinesi", "ice crusher": "Buz kırıcı",
  "saladette": "Salata tezgâhı", "cooling top": "Soğutmalı üst",
  "dishwasher basket": "Bulaşık sepeti", "dishwasher": "Bulaşık makinesi",
  "rinsing basket": "Durulama sepeti", "sink centre": "Evye ünitesi",
  "cutlery polisher": "Çatal-bıçak parlatıcı",
  "dough kneading machine": "Hamur yoğurma makinesi", "dough mixer": "Hamur mikseri",
  "planetary mixer": "Planet mikser", "stick mixer": "El blenderi",
  "hand blender": "El blenderi", "kitchen machine": "Mutfak robotu",
  "meat grinder": "Kıyma makinesi", "vegetable cutter": "Sebze doğrayıcı",
  "slicer": "Dilimleme makinesi", "vacuum packaging machine": "Vakum makinesi",
  "salad spinner": "Salata kurutucu",
  "bain marie": "Benmari", "bain-marie": "Benmari",
  "food warmer": "Yemek ısıtıcı", "chafing dish": "Chafing dish",
  "heating cabinet": "Isıtma dolabı", "hot cupboard": "Sıcak dolap",
  "plate warmer": "Tabak ısıtıcı", "cup warmer": "Fincan ısıtıcı",
  "heat lamp": "Isı lambası", "hot-dog machine": "Sosisli makinesi",
  "buffet trolley": "Büfe arabası", "serving trolley": "Servis arabası",
  "transport trolley": "Taşıma arabası", "clearing trolley": "Toplama arabası",
  "coffee machine": "Kahve makinesi", "coffee grinder": "Kahve değirmeni",
  "percolator": "Perkolatör", "samovar": "Semaver",
  "hot water dispenser": "Sıcak su dispenseri", "kettle": "Su ısıtıcı",
  "mulled wine pot": "Sıcak şarap kazanı", "slush machine": "Slush makinesi",
  "waffle maker": "Waffle makinesi", "crêpe maker": "Krep makinesi",
  "toaster": "Ekmek kızartma makinesi", "conveyor toaster": "Bantlı tost makinesi",
  "popcorn machine": "Patlamış mısır makinesi", "candy floss machine": "Pamuk şeker makinesi",
  "pasta machine": "Makarna makinesi", "pasta mould": "Makarna kalıbı",
  "cutting board": "Kesme tahtası", "chopping board": "Doğrama tahtası",
  "cutting disc": "Kesme diski", "cooking pot": "Tencere", "frying pan": "Tava",
  "gn container": "GN kap", "gn-container": "GN kap", "gn tray": "GN tepsi",
  "baking tray": "Fırın tepsisi", "dishwasher base": "Bulaşık altlığı",
  "insect killer": "Sinek öldürücü", "hand dryer": "El kurutma makinesi",
  "patio heater": "Şemsiye ısıtıcı", "heater": "Isıtıcı",
  "base": "Alt ünite", "insert": "İç kap", "tray": "Tepsi",
  "buffet display": "Büfe vitrini", "buffet showcase": "Büfe vitrini",
  "shelf": "Raf", "cupboard": "Dolap", "cabinet": "Dolap",
  "perforated disk": "Delikli disk", "perforated disc": "Delikli disk",
};

const TIP_ANAHTAR = Object.keys(URUN_TIPI).sort((a, b) => b.length - a.length);

/** Ad başındaki ürün tipini çevir; gerisi (model, ölçü) korunur. */
export function adCevir(ad) {
  const t = String(ad ?? "").trim();
  if (!t) return null;
  const kucuk = t.toLowerCase();
  for (const anahtar of TIP_ANAHTAR) {
    if (kucuk.startsWith(anahtar)) {
      const kalan = t.slice(anahtar.length).trim();
      return kalan ? `${URUN_TIPI[anahtar]} ${kalan}` : URUN_TIPI[anahtar];
    }
  }
  return null;
}
